[package]
name = "parattice"
version = "0.2.1"
authors = ["Koichi Akabe <akabe@xcoo.jp>"]
edition = "2018"

[dependencies]
libc = "0.2.71"

[lib]
name = "parattice"
crate-type = ["rlib", "cdylib", "staticlib"]

[profile.release]
codegen-units = 1
